color_theme = "/usr/share/btop/themes/gruvbox_material_dark.theme"
theme_background = False
truecolor = True
force_tty = False
presets = "cpu:0:block,proc:1:block proc:0:block mem:0:block,proc:0:block"
vim_keys = False
rounded_corners = False
graph_symbol = "block"
graph_symbol_cpu = "block"
graph_symbol_gpu = "block"
graph_symbol_mem = "block"
graph_symbol_net = "default"
graph_symbol_proc = "block"
shown_boxes = "cpu proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = False
proc_per_core = False
proc_mem_bytes = True
proc_cpu_graphs = True
proc_info_smaps = False
proc_left = True
proc_filter_kernel = False
proc_aggregate = False
cpu_graph_upper = "Auto"
cpu_graph_lower = "Auto"
show_gpu_info = "Auto"
check_temp = True
cpu_sensor = "Auto"
show_coretemp = True
temp_scale = "celsius"
base_10_sizes = False
show_cpu_freq = True
clock_format = "%X"
background_update = True
custom_cpu_name = ""
disks_filter = ""
mem_graphs = True
mem_below_net = False
zfs_arc_cached = True
show_swap = True
swap_disk = True
show_disks = True
only_physical = True
use_fstab = True
show_io_stat = True
io_combined = False
io_graph_speeds = ""
net_download = 100
net_upload = 100
net_auto = True
net_sync = False
net_iface = ""
show_battery = True
selected_battery = "Auto"
log_level = "WARNING"
